# Generated by Django 6.0.5 on 2026-05-06 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la campaña')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del anuncio')),
                ('imagen', models.ImageField(help_text='Formatos permitidos: JPG, PNG, GIF', upload_to='anuncios/', verbose_name='Imagen del anuncio')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='gestor.campaña', verbose_name='Campaña')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['-id'],
            },
        ),
    ]
